---
## Playbook for creating mysql cluster
- name: mysql docker cluster
  # i tried to get etcd bare metal and docker to work with tls certs but couldnt figure out how to work with etcdctl etc. to debug
  # so here we are with mysql lmao
  hosts: [etcds]
  tasks:
    - name: Print all available facts (as deliberate gathering to prevent undefined errors later)
      ansible.builtin.debug:
        var: ansible_facts
    - name: initialize docker swarm (to support container overlay network)
      shell: "docker swarm init --advertise-addr 192.168.3.22 && docker swarm join-token -q worker >> worker.txt"
      when: ansible_default_ipv4.address == "192.168.3.22"
    - name: fetch worker token from manager node
      fetch:
        src: worker.txt
        dest: ~/
        flat: yes
      when: ansible_default_ipv4.address == "192.168.3.22"
    - name: copy token to db worker nodes
      copy:
        src: /home/fedora/worker.txt
        dest: $PWD
      when: ansible_default_ipv4.address != "192.168.3.22"
    - name: workers join swarm
      shell: "export TOKEN=$(cat ~/worker.txt) && docker swarm join --token $TOKEN 192.168.3.22:2377"
      when: ansible_default_ipv4.address != "192.168.3.22"
    - name: create docker overlay network via swarm manager node
      shell: "docker network create -d overlay mysqlcluster --attachable --opt encrypted --subnet 172.27.17.0/16"
      when: ansible_default_ipv4.address == "192.168.3.22"
    - name: install docker python libraries
      shell: "pip3 install docker requests"
      environment:
        ansible_python_interpreter: "/usr/bin/python3"
    - name: copy config directory to new directory of same name on EACH host
      copy:
        src: ~/mysql-cluster
        dest: /home/fedora
    - name: setup cluster manager
      community.docker.docker_container:
        name: management1
        image: "mysql/mysql-cluster"
        command: ["ndb_mgmd"]
        detach: yes
        networks:
        - name: "mysqlcluster"
          ipv4_address: "172.27.17.2"
        volumes:
          - ~/mysql-cluster/mysql-cluster.cnf:/etc/mysql-cluster.cnf
          - ~/mysql-cluster/my.cnf:/etc/my.cnf
      when: ansible_default_ipv4.address == "192.168.3.22"
    - name: wait arbitrary period for management node to initialize
      wait_for:
        delay: 90
        timeout: 0
    - name: setup first data node
      community.docker.docker_container:
        name: ndb1
        image: "mysql/mysql-cluster"
        command: ["ndbd"]
        detach: yes
        networks: 
        - name: "mysqlcluster"
          ipv4_address: "172.27.17.3"
        volumes:
          - ~/mysql-cluster/mysql-cluster.cnf:/etc/mysql-cluster.cnf
          - ~/mysql-cluster/my.cnf:/etc/my.cnf
      when: ansible_default_ipv4.address == "192.168.3.23"
    - name: setup second data node
      community.docker.docker_container:
        name: ndb2
        image: "mysql/mysql-cluster"
        command: ["ndbd"]
        detach: yes
        networks:
        - name: "mysqlcluster"
          ipv4_address: "172.27.17.4"
        volumes:
          - ~/mysql-cluster/mysql-cluster.cnf:/etc/mysql-cluster.cnf
          - ~/mysql-cluster/my.cnf:/etc/my.cnf
      when: ansible_default_ipv4.address == "192.168.3.24"
    - name: setup server container
      community.docker.docker_container:
        name: mysql1
        image: "mysql/mysql-cluster"
        command: ["mysqld"]
        detach: yes
        env:
            MYSQL_RANDOM_ROOT_PASSWORD: "true"
        networks:
        - name: "mysqlcluster"
          ipv4_address: "172.27.17.5"
        volumes:
          - ~/mysql-cluster/mysql-cluster.cnf:/etc/mysql-cluster.cnf
          - ~/mysql-cluster/my.cnf:/etc/my.cnf
      when: ansible_default_ipv4.address == "192.168.3.22"
    - name: wait for arbitrary amount of time instead of dynamically responding to listening services
      wait_for:
        delay: 90
        timeout: 0
    - name: test by pulling default root password
      when: ansible_default_ipv4.address == "192.168.3.22"
      shell: "docker logs mysql1 2>&1 | grep PASSWORD"
...
