---
## Separate from and prior to main install to be run as su to avoid privelege errors
- name: open ports on host firewalls
  hosts: etcds
  tasks:
# docker swarm cluster management
    - name: open tcp 2377
      ansible.posix.firewalld:
        state: enabled
        port: 2377/tcp
        permanent: yes
        immediate: yes
# MySQL Cluster management
    - name: open tcp 1186
      ansible.posix.firewalld:
        state: enabled
        port: 1186/tcp
        permanent: yes
        immediate: yes
# MySQL Data ports
    - name: open tcp 2202
      ansible.posix.firewalld:
        state: enabled
        port: 2202/tcp
        permanent: yes
        immediate: yes
# MySQL (?)
    - name: open tcp 3306
      ansible.posix.firewalld:
        state: enabled
        port: 3306/tcp
        permanent: yes
        immediate: yes
# MySQL (?)
    - name: open tcp 33060
      ansible.posix.firewalld:
        state: enabled
        port: 33060/tcp
        permanent: yes
        immediate: yes
# node communication
    - name: open tcp 7946
      ansible.posix.firewalld:
        state: enabled
        port: 7946/tcp
        permanent: yes
        immediate: yes
    - name: open udp 7946
      ansible.posix.firewalld:
        state: enabled
        port: 7946/udp
        permanent: yes
        immediate: yes
# OVERLAY TRAFFIC!!!
    - name: open udp 4789
      ansible.posix.firewalld:
        state: enabled
        port: 4789/udp
        permanent: yes
        immediate: yes
# Reboot
    - name: reboot
      reboot:
# Verify open ports
    - name: list open ports
      shell: "netstat -atu"
...
