---
## Playbook for creating mysql cluster
- name: mysql docker cluster
  hosts: [etcds]
  tasks:
    - name: create docker network
      shell: "docker network create mysqlcluster --subnet=172.17.11.0/16"
    - name: setup cluster manager
      community.docker.docker_container:
        name: management1
        image: "mysql/mysql-cluster"
        command: ["ndbd"]
        detach: yes
        networks:
        - name: "{{ mysqlcluster }}"
          ipv4_address: "172.17.11.2"
      when: ansibe_default_ipv4.address=="192.168.3.22"
    - name: setup first data node
      community.docker.docker_container:
        name: ndb1
        image: "mysql/mysql-cluster"
        command: ["ndbd"]
        detach: yes
        networks: 
        - name: "{{ mysqlcluster }}"
          ipv4_address: "172.17.11.3"
      when: ansible_default_ipv4.address=="192.168.3.23"
    - name: setup second data node
      community.docker.docker_container:
        name: ndb2
        image: "mysql/mysql-cluster"
        command: ["ndbd"]
        detach: yes
        networks:
        - name: "{{ mysqlcluster }}"
          ipv4_address: "172.17.11.4"
      when: ansible_default_ipv4.address=="192.168.3.24"
    - name: setup server container
      community.docker.docker_container:
        name: mysql1
        image: "mysql/mysql-cluster"
        command: ["mysqld"]
        detach: yes
        env:
            MYSQL_RANDOM_ROOT_PASSWORD: "true"
        networks:
        - name: "{{ mysqlcluster }}"
          ipv4_address: "172.17.11.5"
      when: ansible_default_ipv4.address=="192.168.3.22"
    - name: wait for arbitrary amount of time instead of dynamically responding to listening services
      wait_for:
        delay: 60
        timeout: 0
    - name: test by pulling default root password
      when: ansible_default_ipv4.address=="192.168.3.22"
      shell: "docker logs mysql1 2>&1 | grep PASSWORD"
...
